# Generated by Django 5.0.6 on 2024-07-18 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_instance', models.PositiveIntegerField()),
                ('media_path', models.FileField(upload_to='attachments/')),
                ('name', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('O', 'OK'), ('N', 'NO OK'), ('R', 'OBSERVADO')], max_length=1)),
                ('author', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contrast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('O', 'OK'), ('N', 'NO OK'), ('R', 'OBSERVADO')], max_length=1)),
                ('author', models.CharField(max_length=50)),
                ('expiration', models.DateField()),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_comments', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('range', models.CharField(blank=True, max_length=20, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('process_connection', models.CharField(blank=True, max_length=20, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=20, null=True)),
                ('traceable', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(null=True)),
                ('removal_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PatternInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField()),
                ('calibration_lab', models.CharField(max_length=20)),
                ('calibration_number', models.CharField(max_length=20)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SequentialTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=3, unique=True)),
                ('latest', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SetUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gdc_type', models.CharField(max_length=50)),
                ('gdc_number', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('alarm_set', models.FloatField(blank=True, null=True)),
                ('trip_set', models.FloatField()),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('magnitude', models.CharField(choices=[('P', 'PRESION'), ('T', 'TEMPERATURA'), ('N', 'NIVEL'), ('F', 'FLUJO'), ('V', 'VIBRACIONES')], editable=False, max_length=1)),
                ('technology', models.CharField(choices=[('T', 'TRANSMISOR'), ('S', 'SWITCH')], editable=False, max_length=1)),
                ('display', models.CharField(choices=[('I', 'CON INDICACION'), ('X', 'SIN INDICACION'), ('A', 'ABSOLUTAS'), ('R', 'RELATIVAS'), ('P', 'PATRON')], editable=False, max_length=1)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SequencialTag',
        ),
        migrations.AddField(
            model_name='contrast',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrument'),
        ),
        migrations.AddField(
            model_name='check',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrument'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.location'),
        ),
        migrations.AddField(
            model_name='patterninstrument',
            name='instrument',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.instrument'),
        ),
        migrations.AddField(
            model_name='contrast',
            name='p_instrument',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='core.patterninstrument'),
        ),
        migrations.AddField(
            model_name='setup',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrument'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='tag',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tag'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['table', 'table_instance'], name='core_attach_table_i_594c13_idx'),
        ),
    ]
