# Generated by Django 5.0.6 on 2024-07-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attachment_check_contrast_instrument_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='removal_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='display',
            field=models.CharField(choices=[('I', 'CON INDICACION'), ('X', 'SIN INDICACION'), ('A', 'ABSOLUTAS'), ('R', 'RELATIVAS'), ('P', 'PATRON')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='magnitude',
            field=models.CharField(choices=[('P', 'PRESION'), ('T', 'TEMPERATURA'), ('N', 'NIVEL'), ('F', 'FLUJO'), ('V', 'VIBRACIONES')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='technology',
            field=models.CharField(choices=[('T', 'TRANSMISOR'), ('S', 'SWITCH'), ('X', 'SIN TECNOLOGIA')], max_length=1),
        ),
    ]
