# Generated by Django 5.0.6 on 2024-07-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_instrument_removal_date_alter_tag_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
