# Generated by Django 5.0.6 on 2024-07-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_instrument_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrast',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
