# Generated by Django 5.0.6 on 2024-07-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contrast_comments_alter_setup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
