# Generated by Django 5.0.6 on 2024-07-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tag_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
