# Generated by Django 5.0.6 on 2024-08-09 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_check_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrast',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrasts', to='core.instrument'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='core.instrument'),
        ),
    ]
