# Generated by Django 5.0.6 on 2024-08-23 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_contrast_instrument_alter_setup_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrast',
            name='p_instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.patterninstrument'),
        ),
    ]
